apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./server/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: blogs/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: blogs/comments
      context: ./server/comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: blogs/posts
      context: ./server/posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: blogs/event-bus
      context: ./server/event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: blogs/moderation
      context: ./server/moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: blogs/query
      context: ./server/query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .